### ISSUE TITLE
Self-Signup for politicians

### ISSUE THREAD

**Issue by winged** [freedomvote/freedomvote#105]
To avoid administrative overhead / work, it should be possible for politicians to sign up themselves. This should automatically generate an empty profile for them with their personal access URL (possibly the hash of their email address instead of random, to avoid duplication).

The goal is to make it as simple as possible for everyone involved to get a profile online (ourselves, the administrators, the party secretary and the politicians themselves).

**Comment by JohnL17** [comment]
#107

**Comment by JohnL17** [comment]
#107
