### ISSUE TITLE
Autodetect link types

### ISSUE THREAD

**Issue by winged** [freedomvote/freedomvote#11]
Politicians can add links to their Facebook, Twitter etc. Currently, they must declare the type of their link.

This could be detected automatically instead. Then, the user would have one less thing to enter, without any loss of functionality.

**Comment by nicorikken** [comment]
If autodetect is leading, should one be able to override the linktype?
Proposal, regex match when typing, changing the linktype selection box. Done typing (no more automatic selection) the user can select a different linktype.

**Comment by nicorikken** [comment]
More simple solution: default to generic link icon, and try to match URL's to common link types.

**Comment by winged** [comment]
I would remove the explicit types in the DB and just show icons according to what the URL says (ie twitter.com -> twitter icon etc)
