### ISSUE TITLE
Add Portuguese translation

### ISSUE THREAD

**Issue by marado** [freedomvote/freedomvote#13]
This is a feature request. I might tackle this myself sometime in the future.

**Comment by nicorikken** [comment]
@marado how is this coming along? It took me about half an hour to get a rough Dutch translation, which I refined some more afterwards. I don't speak Portugese, but I might be able to help with `.po` files and trying out the rendering.

**Comment by nicorikken** [comment]
@marado For now I'll close this issue, as it seems unlikely it'll go anywhere for now. If you are still willing to contribute a translation, that would still be appreciated.
