### ISSUE TITLE
Enable numeric sort on states

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#15]
In the Netherlands the voting districts (not really states) are also identified by a number. It makes sense to put that number upfront, but then as result the ordering is of. Having the ability to do a numeric sort would be a nice solution. Although the `Kring <num>: <title>` might be difficult to sort, leaving out the `Kring` so the name starts with a number, is a valid alternative. The current sort is also wrong if the description stars with a number (10 before 1).
Another way of dealing with this issue is by enabling a manual ordering of states.
![screenshot from 2016-11-14 21-25-39](https://cloud.githubusercontent.com/assets/7458098/20281719/dfa7f836-aab1-11e6-82c1-883849737f7f.png)

**Comment by nicorikken** [comment]
Suggested solution: add a number field in the model if this is desired.

**Comment by nicorikken** [comment]
Not very important, even in NL the states mainly go by name.

**Comment by andreabettich** [comment]
How about a postcode field?

**Comment by nicorikken** [comment]
I'm not even sure if there is a direct mapping between a postcode and the voting district. Since there seems to be no use-case for now, I'll close this issue.
