### ISSUE TITLE
Add an English translation

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#20]
English is a widely spoken language, so adding this should spread the potential reach for most usages.
I intend to start an English translation soon.

- [x] Initial translation
- [x] Correct translations
- [x] Make pull-request

**Comment by nicorikken** [comment]
I just added a initial English translation on my fork: https://github.com/nicorikken/freedomvote/commit/2dbae3ff18b18e6c32d8c89054bb32dcdad9e36f

**Comment by winged** [comment]
Thanks for PR #40. closing now
