### ISSUE TITLE
Initial edit page returns error

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#33]
After the initial login, e.g. from a different browser, or right after boot, the users gets redirected to `<domain>/<locale>?edit`. This page returns in error. In debug mode this is a stacktrace showing all registered URL paths, in production this would be a `404`.
As this is tied to the initial user experience, getting this fixed would be nice.

![screenshot from 2016-11-14 07-49-23](https://cloud.githubusercontent.com/assets/7458098/20421968/a3e6efa6-ad67-11e6-809c-2801b2d8b76e.png)

* **How to fix?**: Already some middleware is in place, going by the definitions in `settings.py`. Can this be used to handle all registered languages automatically? Othwersie perhaps the local definitions from `settings.py` can be constructed in the `urls.py` to handle all local pages.
* **How to handle?**: Ideally the user would be [redirected](https://stackoverflow.com/questions/15706489/redirect-to-named-url-pattern-directly-from-urls-py-in-django#15706497) to a valid page. Just the frontpage would do.

**Comment by anehx** [comment]
The initial "Home" page is a page which has to be created in the CMS. If this is not done yet, a 404 is the right answer, since there is a page missing..

**Comment by nicorikken** [comment]
The 404 for a missing page makes sense, but the first loaded page is very specific `/<lang>/?edit` and does not resemble any particular page to generate. Why not generate it to a custom page (dev only?) which mentions "You've successfully installed Freedomvote". Or am I overlooking something?

**Comment by nicorikken** [comment]
Fix this by creating a initial database migration.
