### ISSUE TITLE
Authors of French and Italian translations

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#44]
The header information on the translation files for the French and Italian language lack proper author and copyright information. The Git history does not provide the information desired for attribution. Is this available somewhere?

**Comment by andreabettich** [comment]
@winged could probably answer this

**Comment by winged** [comment]
Update: I did find some notes in my email archive from Nicolas around September 11 2015, so maybe @nikslor can give a definitive answer, as he was the one who sent out the request to the translation company.

**Comment by winged** [comment]
Info for Adfinis guys: Here's the relevant ticket in our system: https://project.adfinis-sygroup.ch/issues/11732

**Comment by nicorikken** [comment]
The question then becomes whether or not copyright was transferred.

**Comment by swaechter** [comment]
The French and Italian translation was written by our fellow Gian-Maria Daffré (gian-maria.daffre@giammi.com), so he is the author of the translations.

**Comment by nicorikken** [comment]
Thanks @swaechter . Especially since we're talking volunteering work here, I'll happily add the copyright details. In the mean time some of the translations are outdated, so now we could contact the authors if they are willing to update their translations.
P.S.: if you have remarks on or wishes for the current Freedomvote progress, I'd be glad to hear about them.

**Comment by swaechter** [comment]
I am really pleased to see that a group is able to reuse Freedomvote! Is there already a live system which we can show other people?

**Comment by nicorikken** [comment]
Nope, working on it right this moment. I'm still experiencing some minor issues in reusing an existing deploy script: https://github.com/freedomvote/freedomvote/issues/66 I'm very pleased there were people pioneering this tooling in the first place :wink:
