### ISSUE TITLE
Statistics / calculations are not correct in every case

### ISSUE THREAD

**Issue by winged** [freedomvote/freedomvote#5]
The `Statistic` table stores the average of points of the politician's answers. This average in turn is then compared with the average of our "desired answers".  This only works as long as the desired answers are either 0 or 10.

If for example the "desired answer" is set to 4 on one question and 10 on the other, we cannot discriminate between a politician answering with 4/10 (perfect match) and 10/4 (which should be further away).

**Comment by nicorikken** [comment]
I'm still in the process of getting to understand the deepest details of Freedomvote, so please correct me:
Would this be fixed if the sum (all questions) of the absolute difference (per question) between the desired and answered value would be registered? The larger the value, the greater the difference of opinion. If the value is 0, then the answers were ideal.
Still, if the answers of visitors are compared, it would still have to be compared on the level of each individual question.
How does this work currently, and how best to fix this?

**Comment by nicorikken** [comment]
For now not considered as important to fix, as it can be circumvented by setting the correct answers. Or does this conflict with users opinion as well?
