### ISSUE TITLE
Add party logos

### ISSUE THREAD

**Issue by anehx** [freedomvote/freedomvote#6]
Let parties include their logo or generate ([like this](http://www.politnetz.ch/artikel/21758-vier-fragen-zur-familieninitiative-ja-mein-interview-auf-politnetz)) a simple svg with their shortname.

Display the logo instead of the party shortname in the list or detail view.

**Comment by nicorikken** [comment]
As suggested, having a box around text, as shown below:
![screenshot from 2016-12-09 16-53-42](https://cloud.githubusercontent.com/assets/7458098/21055016/1b02d766-be30-11e6-852e-15a5ee960118.png)

Alternative is to have upload functionality.

**Comment by nicorikken** [comment]
Alternative is to fix it using CSS styling. Ideally have different colors for different parties, to ease visual distinction.
