### ISSUE TITLE
Scripted deploy

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#66]
I'm working on a deploy based on Ansible. The Docker option is an alternative solution for deploy, but that was less ideal at my hosting party.

I'm basing the deploy now on [Ansible Django Stack](https://github.com/jcalazan/ansible-django-stack) playbook. It seems to offer a well-developed default setup, including some performance optimizations (Nginx, WSGI) and comes with a set of security enhancements like safe automatic updates and fail2ban.

The project structure of the reference project [Youtube Audio dl](https://github.com/jcalazan/youtube-audio-dl) is a little different than the structure of Freedomvote, which implies some changes are needed.

**Findings thus far**
- Pillow could not be built without having the correct packages. This got solved by installing them:  https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux#34631976
- The `manage.py` in Freedomvote is located in the `app/` directory. By changing the `app-path` in `roles/web/tasks/setup_django_app.yml`
- The `host` of the `default` database in the `settings.py` is set to `'db'` by default. This is not a proper address. Something like `127.0.0.1` is expected. This is noted in the `README.md` as having to add the `app/settings.ini`. For now I've hardcoded it, but a `settings.ini` file might do as well.
- The Nginx config of `roles/nginx/templates/youtubeadl.j2` needs to be duplicated for `freedomvote.j2`.
  - The plain duplication results in a 404 on the root, so the config will have to be changed. **This is still work in progress**

**Comment by andreabettich** [comment]
When I remember right, I had to run ´sudo apt install libjpeg8-dev libpq-dev python-dev´ to get everything running on my Ubuntu 16.04 machine.

**Comment by nicorikken** [comment]
It seems that Supervisor cannot get Freedomvote to run:
*Snippet from /var/log/supervisor/supervisord.log*
```
2017-01-14 11:13:47,254 INFO spawned: 'freedomvote' with pid 3090
2017-01-14 11:13:48,284 INFO success: freedomvote entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-01-14 11:13:48,400 INFO exited: freedomvote (exit status 3; not expected)
```

**Comment by andreabettich** [comment]
Weird. Do you have the ansible playbook files in a branch of you?

**Comment by nicorikken** [comment]
I just uploaded my recent changes to https://github.com/nicorikken/ansible-django-stack on the `master` branch.

**Comment by nicorikken** [comment]
It seems that Gunicorn isn't coming up, Nginx seems to run fine, although hard file links are wrong.

**Comment by nicorikken** [comment]
In `/webbapps/freedomvote/logs/gunicorn_supervisor.log` it reads: `ImportError: No module named freedomvote.wsgi`

**Comment by nicorikken** [comment]
Changing the paths around in the files, I'm now getting a Django error page served. It seems Django cannot successfully operate, partly because the site_id cannot be resolved:

```Environment:


Request Method: GET
Request URL: https://192.168.33.15/

Django Version: 1.8
Python Version: 2.7.6
Installed Applications:
('modeltranslation',
 'colorfield',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_admin_bootstrapped',
 'django.contrib.admin',
 'django.contrib.messages',
 'treebeard',
 'menus',
 'sekizai',
 'djangocms_admin_style',
 'djangocms_text_ckeditor',
 'easy_thumbnails',
 'piwik',
 'core',
 'api',
 'cms',
 'meta')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware')


Traceback:
File "/webapps/freedomvote/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  108.                 response = middleware_method(request)
File "/webapps/freedomvote/local/lib/python2.7/site-packages/cms/middleware/toolbar.py" in process_request
  117.         request.toolbar = CMSToolbar(request)
File "/webapps/freedomvote/local/lib/python2.7/site-packages/cms/toolbar/toolbar.py" in __init__
  98.             toolbar = toolbars[key](self.request, self, toolbars[key].check_current_app(key, self.app_name), self.app_name)
File "/webapps/freedomvote/local/lib/python2.7/site-packages/cms/toolbar_base.py" in __init__
  16.         self.current_site = Site.objects.get_current()
File "/webapps/freedomvote/local/lib/python2.7/site-packages/django/contrib/sites/models.py" in get_current
  60.             return self._get_site_by_id(site_id)
File "/webapps/freedomvote/local/lib/python2.7/site-packages/django/contrib/sites/models.py" in _get_site_by_id
  39.             site = self.get(pk=site_id)
File "/webapps/freedomvote/local/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/webapps/freedomvote/local/lib/python2.7/site-packages/django/db/models/query.py" in get
  334.                 self.model._meta.object_name

Exception Type: DoesNotExist at /
Exception Value: Site matching query does not exist.
```

This is a Stackoverflow thread which seems to be related: https://stackoverflow.com/questions/23925726/django-relation-django-site-does-not-exist#34274950

**Comment by nicorikken** [comment]
YEAH!!! Fixing the migrations in https://github.com/freedomvote/freedomvote/issues/68 was part of the solution. With migrations fixed, I can call the migrations to get the database in the correct state. Now the static files are not correctly configured, which is still something to fix.

**Comment by andreabettich** [comment]
Nice to hear that you fixed it. :+1

**Comment by nicorikken** [comment]
The Nginx config is still giving issues. I tried with a config having this excerpt:

```
location /static/ {
        alias   /webapps/freedomvote/freedomvote/app/core/static;
    }

    location /media/ {
        alias   /webapps/freedomvote/freedomvote/app/media/;
    }
```
Still I get 404's on all requests. Let alone how to deal with relative URL's like `static/admin/css/overrides.css` used in the admin interface, which seem to lack a direct mapping with the static files.
I tried to brute-force some nesting levels, but no luck, Perhaps I'm misunderstanding how to config the Nginx aliases.

**Comment by nicorikken** [comment]
Going through the Ansible config with the changes, it seems Django also needs to be aware of the paths, so perhaps changing it in the Ansible variables, rather than on the configured box itself, might work.

**Comment by nicorikken** [comment]
Nope, changing the aliases through the Ansible config didn't change the outcome. Also triggering the syncdb is still needed in order to resolve the `site_id` issue.

**Comment by nicorikken** [comment]
@andreabettich could you perhaps checkout my Ansible branch https://github.com/nicorikken/ansible-django-stack and run `vagrant up` and see what could have gone wrong using `vagrant ssh`? I start debugging by calling `source /webapps/freedomvote/bin/activate` to get your shell sourced with the right variables.

**Comment by andreabettich** [comment]
Yea, I'm currently on it :wink:

**Comment by nicorikken** [comment]
@andreabettich thanks, your changes made it work!!! Do you want to merge this, or fork it into the freedomvote GitHub organization.

**Comment by nicorikken** [comment]
@andreabettich as you mentioned in Slack, I too get an error when trying to run `vagrant provision` after the initial `vagrant up`:
```
TASK [db : Ensure user has access to the database] *****************************
task path: /home/nico/Software/ansible-django-stack/roles/db/tasks/main.yml:32
fatal: [default]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible__m_pDm/ansible_module_postgresql_user.py\", line 666, in <module>\r\n    main()\r\n  File \"/tmp/ansible__m_pDm/ansible_module_postgresql_user.py\", line 621, in main\r\n    changed = user_alter(cursor, module, user, password, role_attr_flags, encrypted, expires, no_password_changes)\r\n  File \"/tmp/ansible__m_pDm/ansible_module_postgresql_user.py\", line 293, in user_alter\r\n    cursor.execute(' '.join(alter), query_password_data)\r\n  File \"/usr/lib/python2.7/dist-packages/psycopg2/extras.py\", line 123, in execute\r\n    return _cursor.execute(self, query, vars)\r\npsycopg2.ProgrammingError: must be superuser to alter replication users\r\n\r\n", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/home/nico/Software/ansible-django-stack/vagrant.retry
```

Extracted:

**stderr**
`Shared connection to 127.0.0.1 closed.`

**stdout**
```
Traceback (most recent call last):
  File \"/tmp/ansible__m_pDm/ansible_module_postgresql_user.py\", line 666, in <module>
    main()
  File \"/tmp/ansible__m_pDm/ansible_module_postgresql_user.py\", line 621, in main
    changed = user_alter(cursor, module, user, password, role_attr_flags, encrypted, expires, no_password_changes)
  File \"/tmp/ansible__m_pDm/ansible_module_postgresql_user.py\", line 293, in user_alter
    cursor.execute(' '.join(alter), query_password_data)
  File \"/usr/lib/python2.7/dist-packages/psycopg2/extras.py\", line 123, in execute
    return _cursor.execute(self, query, vars)
psycopg2.ProgrammingError: must be superuser to alter replication users
```

**Comment by nicorikken** [comment]
In my own changes to make this work, I hardcoded the URL in the settings. I want to make a template in Ansible to write the settings file, which seems the proper way.

**Comment by nicorikken** [comment]
It seems that I've got it in a working order now. I've changed the Freedomvote project to fix the migration issue https://github.com/freedomvote/freedomvote/issues/68 and I've created a pull-request which creates a `settings.ini` file to override the `settings.py` for the database configuration: https://github.com/nicorikken/ansible-django-stack/commit/087a3b7721b531911d543a4c8005d055f2ba50f9 **Should the Ansible code be included in the project?** (might be harder to keep up to date with upstream though)

**Comment by nicorikken** [comment]
It seems that no default CMS admin user was created in the Ansible deploy. The example project seems to have an admin predefined, although no password is listed: https://github.com/jcalazan/youtube-audio-dl/blob/master/youtubeadl/settings/base.py#L161-L163 Perhaps the users will have to be added using database migrations or commandline calls?

**Comment by nicorikken** [comment]
In trying to find out how to create a default superuser, I found that setting a password requires an interactive session. As this is quite easy, I think this can be left out from the Ansible playbook:
```
ssh user@myfreedomboxinstallation.org
source /webapps/bin/activate
cd /webapps/freedomvote/app
python manage.py createsuperuser
```

**Comment by andreabettich** [comment]
I did it this way yesterday evening when testing.

**Comment by nicorikken** [comment]
@andreabettich, regarding the integration of the Ansible code, you opted to pull the Ansible playbook into the Freedomvote organization, and perhaps include it into the code as a submodule. Should I clean it up, or is it good enough to pull into the organization? https://github.com/nicorikken/ansible-django-stack/commits/master

**Comment by andreabettich** [comment]
@nicorikken Doesn't matter if you delete the unused first and then move it or if you move it and then remove the unused stuff. It's up to you :wink:

**Comment by nicorikken** [comment]
Check, just made a small improvement to link to the freedomvote/freedomvote repo instead of my own. Can you pull it into the Freedomvote organization then?

**Comment by nicorikken** [comment]
I still have to test the security features  of the playbook (including the letsencrypt certificates), but as they operate on the OS level, I see no real issues there. Either way I can deploy it in this current state. If needed I'll make some PR's.

**Comment by nicorikken** [comment]
Apparently I had enough rights to fork it myself: https://github.com/freedomvote/ansible-django-stack
