### ISSUE TITLE
Page edit seems broken

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#67]
I'll have to look further to see if I can get this resolved, but for now the page edit is broken.
Having created a page in the CMS, I get a blank page rather than a proper edit page.
![screenshot from 2017-01-15 01-20-15](https://cloud.githubusercontent.com/assets/7458098/21961773/935da196-db13-11e6-9388-cdc4a0e844a6.png)

I'm weary that the *initial page edit* commit https://github.com/freedomvote/freedomvote/commit/559b72fc76cc2ebe3acab25430b7b3a3c8e924c4 might have messed things up, even though the welcome page was successfully rendered.

**Comment by nicorikken** [comment]
![screenshot from 2017-01-22 20-38-56](https://cloud.githubusercontent.com/assets/7458098/22185282/edae0332-e0e2-11e6-9692-0f8c4686e358.png)
Perhaps the error in the console has to do with it. I tried to revert to the commit https://github.com/freedomvote/freedomvote/commit/9bda9dd2c956d45156a7cf6d9d09da9dd44e4073 but without any success.

**Comment by nicorikken** [comment]
Is there some workaround through the database to get the page content loaded?

**Comment by nicorikken** [comment]
Also I did a diff with the original Freedomvote code (before I joined), but could not find anything related to the static pages. Perhaps this was broken even earlier?

**Comment by nicorikken** [comment]
Going by some of the search results, I tried to include the `{% cms_toolbar %}` which results in a rendered top toolbar, but doesn't fix the issue of the lack of editing options.
![screenshot from 2017-01-22 22-13-34](https://cloud.githubusercontent.com/assets/7458098/22186055/153e0da4-e0f0-11e6-9234-c01133f28f65.png)

**Comment by nicorikken** [comment]
The editing plugins can still be called by their individual URL's. They are just not shown. E.g. consider `http://localhost:8000/admin/cms/page/edit-plugin/1/` to edit the first page.

**Comment by nicorikken** [comment]
Perhaps this GitHub issue tread might shine a light on the issue at hand: https://github.com/divio/djangocms-text-ckeditor/issues/47

**Comment by nicorikken** [comment]
Running Freedomvote in a local Vagrant setup, I see no `edit-plugin` link, and only get errors for 2 plugins rather than 3. I get the sense that the editing option on my local install (not Vagrant) has an edit, as it was created in the beginning of my commits to the Freedomvote project, and therefore already had a page in its database. The Vagrant setup is brand new, therefore lacks any created page, and the plugins to actually create some contents in the page are not loaded.
This makes sense. The CMS edit functionality needs to be restored, before the page contents can be initiated, and edited. Now it is just an empty page that can be created from the admin panel.

**Comment by andreabettich** [comment]
The PR #70 should fix the toolbar issue.

**Comment by nicorikken** [comment]
Great! I've tested it locally and it works. Still, I would like to have the ability to add images. I guess we need an additional plugin for that.
