### ISSUE TITLE
Minimal bar width in mouseover diagrams

### ISSUE THREAD

**Issue by winged** [freedomvote/freedomvote#7]
When hovering over the aggregated match of a politician (see picture below), the popup diagram may show a missing bar for an answer category. This could be interpreted as a bug. However the case here is that the matching level of the politician in this category is just zero, resulting in no bar shown at all.

To improve user understanding, it would be helpful to show at least a small bar even if the match is zero.

![missing_e_voting](https://cloud.githubusercontent.com/assets/303759/12168170/d03d1d4e-b530-11e5-8901-69bd81f006ba.png)

**Comment by nicorikken** [comment]
Another possible solution: filling the rest the bar with an off-white color (or light grey), to show the presence of a bar.

**Comment by nicorikken** [comment]
Alternative: render a 2px width bar.
