### ISSUE TITLE
CMS images

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#71]
Currently only the text plugin is available in the CMS, so no images can be included. Ideally images can be included, like logo's.

**Comment by nicorikken** [comment]
@andreabettich what plugins were used for the Swiss edition?

**Comment by nicorikken** [comment]
I found the addon [djangocms-picture](https://github.com/divio/djangocms-picture) which can seemingly provide a UI-based interface for adding images.

Another option is just to type HTML, as is seemingly used for the original Swiss page. An excerpt:
```
<div class="col-md-3">
  <img alt="Bundeshaus" class="img-responsive img-rounded" src="static/images/bundeshaus.jpg" /> 
  <em class="source">Quelle: <a href="http://www.parlament.ch">http://www.parlament.ch</a></em>
</div>
```

It is interesting to know how the Nginx setup deals with this. The `collectstatic` command should be enough to get the images in the static dir, ready to be served by Nginx. https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/

**Comment by nicorikken** [comment]
Apparently you can still copy an image into the box (Firefox and IE). Yet it seems to be served by the Python code, rather than by Nginx. An alternative setup is to use `django-filer`, and it can be integrated with the regular editing plugin. I get the feeling there should be a better setup available though.

**Comment by andreabettich** [comment]
Don't know what is used on the Swiss Freedomvote site for the images.
Maybe @winged knows something

**Comment by nicorikken** [comment]
For now I'll probably just put them in `static/` myself.

**Comment by nicorikken** [comment]
Can be worked around.
