### ISSUE TITLE
Menu disappears

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#72]
Having created a page in English and Dutch, the menu option of the page disappears when navigating to the page itself.

Opening the homepage.
![screenshot from 2017-01-25 07-28-01](https://cloud.githubusercontent.com/assets/7458098/22280258/e282f618-e2cf-11e6-9573-1f5ac0c4192a.png)

After clicking on the 'about' menu option.
![screenshot from 2017-01-25 07-28-13](https://cloud.githubusercontent.com/assets/7458098/22280259/e2a558de-e2cf-11e6-9046-afcf86add37b.png)

Perhaps I messed up while creating the page, somehow.

**Comment by andreabettich** [comment]
Thats kind of weird. I'll take a look today

**Comment by nicorikken** [comment]
Fixed by @andreabettich in commit https://github.com/freedomvote/freedomvote/commit/e656679e0a85ee85de1c4923dee68c5dd8612200
