### ISSUE TITLE
Footer as a static placeholder?

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#74]
Django CMS has the ability to serve content for static placeholders. This would be parts of the page like the footer. The Swiss Freedomvote page has a nice footer, decorated with the logos of associated organizations. By opening this up for editing in the CMS, changes can be done more easily (for non-technical users).

**Comment by andreabettich** [comment]
Good idea. Would make it more Editor friendly

**Comment by nicorikken** [comment]
Is it good enough to have a static placeholder in which HTML tags have to be used?

**Comment by nicorikken** [comment]
I think it is good enough. The same goes for the other elements on the page.
