### ISSUE TITLE
The politician edit URL base URL is not correct

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#76]
![screenshot from 2017-01-29 22-34-47](https://cloud.githubusercontent.com/assets/7458098/22408102/371f878a-e673-11e6-8c8b-ac8991b5f819.png)
It seems some internal variable is not set correctly.

**Comment by nicorikken** [comment]
This is probably a faulty setting on my side. Still it would be nice if it were fixed.

**Comment by andreabettich** [comment]
You can set the URL in the `settings.py` under DEFAULT_SETTINGS.GLOBAL.BASE_URL
