### ISSUE TITLE
Public access for politician spider

### ISSUE THREAD

**Issue by anehx** [freedomvote/freedomvote#9]
Politicians should be able to embed their spider in their own site. The link should be displayed in their private edit view but should only use their public access key (ID).

**Comment by nicorikken** [comment]
First enable easy reference by public id. Second offer an embed feature.

**Comment by nicorikken** [comment]
Rendering is done client-side, but data-url is public and unique. Perhaps have a dedicated view (page) with just the spider, which can then be included in an iframe.

**Comment by nicorikken** [comment]
Maybe this might be of help: http://www.highcharts.com/cloud/how-to-share-on-blogs-webpages/embed-without-iframe
