### ISSUE TITLE
Evaluate answer not available without save

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#92]
When filling in answers in the comparison view, one has to first save the answers, and then in a seperate action evaluate the answers to view the results. More intuitively would be to evaluate and save in one action.
Users will now have to go through more stages:
`home -> [compare] -> questions -> [save] -> [evaluate] -> comparison`
I'd like to move towards:
`home -> [compare] -> questions -> [evaluate] -> comparison`

**Comment by nicorikken** [comment]
Tempate: https://github.com/freedomvote/freedomvote/blob/master/app/core/templates/core/compare/index.html
Associated javascript: https://github.com/freedomvote/freedomvote/blob/master/app/core/static/js/compare.js
I assume I'd have to adjust the Javascript. Yet I do not see how I can combine the save and evaluate buttons.
Perhaps I can include a redirect with the 'save' feature and rename it?

**Comment by andreabettich** [comment]
I'll take a look on my train ride.

**Comment by andreabettich** [comment]
The JS just adds some values to another field.
https://github.com/freedomvote/freedomvote/blob/master/app/core/views.py#L137
Here you have to do something when the compare form makes a POST request to it. I have something that is working half way, but needs some improvements.

**Comment by nicorikken** [comment]
Something like this https://stackoverflow.com/questions/29649954/django-python-how-to-create-redirect-from-one-view-url-to-another#29650087, so providing a redirect in the response.
